### PR TITLE
Env config

### PR DESCRIPTION
**Pull request by nicolasblaye**
This enable the server to be deployed on other env.

I changed the config to json because I couldn't add a list in the current config file, and also to add the id part to identify the different pogo servers

### CODE REVIEW

**Comment by tama** [comment]
Suggestion : add an "environment name" (or "development": true/false) in the configuration

**Comment by nicolasblaye** [comment]
How would we use it? To what end?

**Comment by tama** [comment]
dev = true => Read from configuration file, set "dev" or "debug" flag

Use case :
```
if debug is True:
  reply_with_stacktrace()
```

**Comment by nicolasblaye** [comment]
Shouldn't this be a separate PR about logging and CI/CD? We can put whatever we want in the config anyway.

**Review by tama — APPROVED** [review]

**Pull request merged**
